{% set name = "mrcfile" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3a113042d24820b9dfc6902cb9d93bcbebdee22beb40552f2c35303ace4b0547

build:
  number: 0
  entry_points:
    - mrcfile-header = mrcfile.command_line:print_headers
    - mrcfile-validate = mrcfile.validator:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.12.0
    - pip
    - python
  run:
    - numpy >=1.12.0
    - python

test:
  imports:
    - mrcfile
  commands:
    - mrcfile-header --help
    - mrcfile-validate --help

about:
  home: "https://github.com/ccpem/mrcfile"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "MRC file I/O library"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
